### ISSUE TITLE
Failed to find NEWT Display Class <.windows.DisplayDriver>

### ISSUE THREAD

**Issue by lj52man** [elect86/jogl-samples#14]
![image](https://cloud.githubusercontent.com/assets/8624600/12258480/fae868ba-b949-11e5-896d-41f6384b26dc.png)

**Comment by lj52man** [comment]
Hi, need your help.I run your 'jogl-samples' project in eclipse, I select the helloTriangle.HelloTriangle.java to run, but error happened.

**Comment by elect86** [comment]
Hi lj52man,

jogl version?

**Comment by elect86** [comment]
Ps: be sure the native are located in the same directory.

https://jogamp.org/wiki/index.php/Setting_up_a_JogAmp_project_in_your_favorite_IDE

I created a lib called `jogl`, substitute the jar in that folder with those of your just-download (jogamp-all-platforms.7z)[http://jogamp.org/deployment/jogamp-current/archive/jogamp-all-platforms.7z]

**Comment by elect86** [comment]
Hey lj52man,

solved? :)

**Comment by elect86** [comment]
I am gonna close it, if you need help, just pop up  :wink:
